
/*

    SCHEMA FOR USERS TABLE

*/

CREATE TABLE IF NOT EXISTS `my_app`.`users` (
`u_id` INT( 10 ) UNIQUE NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`email` VARCHAR( 100 ) UNIQUE NOT NULL ,
`first_name` VARCHAR( 40 ) NOT NULL ,
`last_name` VARCHAR( 40 ) NOT NULL ,
`password` VARCHAR( 64 ) NOT NULL
) ENGINE = InnoDB;